#!/usr/bin/env bash
# papers/wording/generate.sh                                       -*-sh-*-
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Regenerates the [expected] clause wording from the annotated headers in
# include/beman/expected/, via specgen (https://github.com/steve-downey/specgen).
# Each header is one specgen document. Their IR is rendered together so
# validation sees the paper-wide union of documented names.
#
# Produces:
#   papers/wording/fragments/*.tex  - one fragment per top-level clause, for
#                                      \input into a paper's own
#                                      \rSec1[expected]{Expected objects}.
#   papers/wording/expected.tex     - all fragments concatenated in real
#                                      standard clause order. This is the
#                                      "wording only" file: plain generated
#                                      prose, with no \input directives,
#                                      suitable as the basis for a diff
#                                      against the actual draft
#                                      (github.com/cplusplus/draft)
#                                      source/utilities.tex.
#
# specgen must be on PATH. Run from anywhere; paths below are relative to
# this script's location.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/../.." && pwd)"
include_dir="$repo_root/include"
fragments_dir="$here/fragments"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

clang_args=(-std=c++2c -I "$include_dir")
if [[ -n "${SPECGEN_GCC_TOOLCHAIN:-}" ]]; then
    clang_args+=("--gcc-toolchain=$SPECGEN_GCC_TOOLCHAIN")
fi

mkdir -p "$fragments_dir"

generate_ir() {
    local header="$1"
    local ir="$2"

    echo "Generating IR from $header..." >&2
    specgen generate "$include_dir/beman/expected/$header" \
        --emit-ir --no-compile-commands \
        -o "$work_dir/$ir" \
        -- "${clang_args[@]}"
}

generate_ir unexpected.hpp unexpected.json
generate_ir bad_expected_access.hpp bad_expected_access.json
generate_ir expected.hpp expected.json

render_dir="$work_dir/rendered"
echo "Rendering and validating the three-header paper..." >&2
specgen render \
    --from-ir "$work_dir/unexpected.json" \
    --from-ir "$work_dir/bad_expected_access.json" \
    --from-ir "$work_dir/expected.json" \
    --root expected.unexpected.root \
    --root expected.bad.root \
    --root expected.root \
    --backend latex --validate \
    --base-section-depth 2 \
    --split "$render_dir"

# Map specgen's stable-name-derived filenames to the fragment names we keep.
cp "$render_dir/expected.unexpected.tex" "$fragments_dir/unexpected.tex"
cp "$render_dir/expected.bad.tex"        "$fragments_dir/bad.tex"
cp "$render_dir/expected.bad.void.tex"   "$fragments_dir/bad-void.tex"
cp "$render_dir/expected.expected.tex"   "$fragments_dir/object.tex"
cp "$render_dir/expected.void.tex"       "$fragments_dir/void.tex"
cp "$render_dir/expected.ref.tex"        "$fragments_dir/ref.tex"

# Any root fragments contain declarations outside generated clauses, including
# exposition-only implementation helpers. They are not part of the standard's
# own wording (the real draft states an equivalent helper, reinit-expected,
# inline in [expected.object.assign]'s own intro instead) and are intentionally
# omitted from the assembled clause below.

out="$here/expected.tex"
{
    echo '% papers/wording/expected.tex                                      -*-LaTeX-*-'
    echo '% SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception'
    echo '%'
    echo '% Generated by papers/wording/generate.sh from the annotated headers in'
    echo '% include/beman/expected/ via specgen. Do not edit by hand: re-run'
    echo '% generate.sh after changing a header'\''s //! docblocks instead.'
    echo '%'
    echo '% --base-section-depth 2 puts each \rSec marker at the level the draft'
    echo '% writes it at: [expected.unexpected] and its siblings are \rSec2, their'
    echo '% subclauses \rSec3, numbering 22.8.3, 22.8.3.1, ... just as in'
    echo '% source/utilities.tex. This file is therefore everything that sits'
    echo '% *inside* the existing \rSec1[expected]{Expected objects} in the draft'\''s'
    echo '% source/utilities.tex, in clause order, ready to replace the current'
    echo '% [expected.unexpected] through [expected.void] subclauses and add the new'
    echo '% [expected.ref] one after them -- no \rSec1[expected] wrapper and no'
    echo '% \input directives. [expected.general] and [expected.syn] are prose, not'
    echo '% generated from any one declaration; see papers/expected-new.tex.'
    echo
    sep=""
    for f in unexpected.tex bad.tex bad-void.tex object.tex void.tex ref.tex; do
        printf '%s' "$sep"
        cat "$fragments_dir/$f"
        sep=$'\n'
    done
} > "$out"

echo "Wrote $out" >&2
echo "Wrote $fragments_dir/{unexpected,bad,bad-void,object,void,ref}.tex" >&2
