# Standard answers and internal state managed by Copier
_commit: v2.4.0-40-g8bf7fea
_src_path: https://github.com/steve-downey/exemplar.git
description: Expected Over References
maintainer: steve-downey
minimum_cpp_build_version: '20'
paper: PnnnnRr
project_name: expected
unit_test_library: catch2
# Hidden variables manually tracked because 'when: false' omits them from _copier_answers
generating_exemplar: false
owner: "bemanproject"
ci_tests_cron: "15 12 * * 2"
pre_commit_update_cron: "50 7 * * 4"
