# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: vcpkg registry release
on:
  release:
    types: [published]
jobs:
  vcpkg-release:
    permissions: {}
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-vcpkg-release.yml@1.7.3
    with:
      port_name: beman-expected
    secrets:
      VCPKG_REGISTRY_TOKEN: ${{ secrets.VCPKG_REGISTRY_TOKEN }}
